### PR TITLE
Adding new link and file

### PR DESCRIPTION
**Pull request by mkalish**
People can find out about the data portal and submit requests for new data sources

### CODE REVIEW

**Comment by stvnrlly** [comment]
I am 👍 on this, but have one question: would it be better to just link straight to the site and put the content from the new page there, instead?

**Comment by mkalish** [comment]
So I'm about 25% in to writing a CKAN plugin that we could embed this directly into data.codefordc.org.  I viewed this a stopgap, but at this point it might be easier just to wait rather than introduce one way and immediately introduce another.

**Comment by stvnrlly** [comment]
That requires a plugin? Doesn't sound like much fun. If that won't take too long, let's just do a direct link.

**Comment by stvnrlly** [comment]
@mkalish what would you like to do here?

**Comment by mkalish** [comment]
@stvnrlly I'm going to go ahead and close this.  I'm pretty close to getting the form added into the data portal directly.

**Pull request closed without merging**
