### PR TITLE
adding the code for dc hack night calendar to the home page

### PR DESCRIPTION
**Pull request by mkalish**
Screenshot:

screen shot 2017-05-18 at 8 03 21 pm

### CODE REVIEW

**Comment by trycrmr** [comment]
In reviewing the site I got thinking about what agenda view would look like instead of the calendar view. The calendar can take up about half the vertical space and we typically only have two events a month, so the month view looks pretty sparse.
 
screen shot 2017-05-21 at 12 09 11 pm

**Comment by trycrmr** [comment]
Oops, left the border in on the screenshot ☝️ . No border, IMO.

**Comment by mkalish** [comment]
I think I turned on a bunch of our calendars though?  Maybe the agenda view still makes sense, if the calendar continues to be sparsely populated

**Comment by trycrmr** [comment]
👌

**Pull request merged**
