### PR TITLE
civic.json v2

### PR DESCRIPTION
**Pull request by stvnrlly**
This proposes some updates to the civic.json specification, to make the files a little more maintainable.

It removes:
- needs
- categories
- politicalEntity
- bornAt

And adds:
- tags

The `tags` array is important because it is one of two fields (along with `status`) that the Code for America API actually pulls in. Most `categories` should be able to become `tags`, but the latter is potentially broader than the former. The `needs` object should be removed because it quickly gets out of sync with the actual needs of the project. A better solution may be tagging issues or something like Trello.

If this is merged, we'll want to run through the existing tracked files and submit updates. Also, the projects page will need to be updated to remove the needs and categories displays.

### CODE REVIEW

**Comment by emanuelfeld** [comment]
Thoughts:

1. I think there's a need to have an attribute that basically gives what organization/group the thing is affiliated with. I would even say two attributes, e.g. "top_level_attr": "Code for DC", "second_level_attr": "District Housing" kind of deal. This would also have the added benefit of being more interoperable across organization (Code for DC-DCgov-whatever else).
2. Might want to broaden what's acceptable for contact. Some cases may warrant a contact form, rather than your email address (especially for team projects).
3. It would be more generalizable (without sacrificing anything) if there were just a "partners" attribute, rather than communitypartners and governmentpartners.

**Comment by stvnrlly** [comment]
Hmm, how about an `entities` object that includes all involved orgs? For example:

```
entities: [
  {"name": "Code for DC",
   "type": "lead",
   "url": "codefordc.org"},
  {"name": "Bread for the City",
   "type": "community partner",
   "url": "breadforthecity.org"}
]
```

I think I'm missing what you're saying about top-level and second-level attributes, though? Do you mean subgroups of the entities?

**Comment by emanuelfeld** [comment]
Yeah, essentially subgroups. For instance, a repo may be maintained by the DDOT GIS team or the DDOT Traffic team. It's helpful to be able to attribute it to DDOT, but also specify the group actually working on it.

(Basically trying to see if we can converge on a standard that both Code for DC and DCgov can use)

**Comment by stvnrlly** [comment]
How about `parent` as a key within the `entities` object? Example:

```
entities: [
  {"name": "DDOT GIS team",
   "type": "lead",
   "url": "website.gov",
   "parent": "DDOT"}
]
```

We could also make `parent` an object with `name` and `url` fields. Or, we could allow `top-level lead` and `second-level lead` as `type` values.

**Comment by emanuelfeld** [comment]
I'm inclined to your second suggestion. It's best to avoid too much nesting.

**Comment by emanuelfeld** [comment]
Proposal (though unsure about team vs. entities):

	{
	  "specification": "",
	  "status": "",
	  "thumbnailUrl": "",
	  "team": [
	    {
	      "name": "",
	      "url": "",
	      "role": ""
	    }
	  ],
	  "entities": [
	    {
	      "name": "",
	      "url": "",
	      "role": ""
	    }
	  ],
	  "geography": "",
	  "type": "",
	  "data": [
	    {
	      "name": "",
	      "url": ""
	    }
	  ],
	  "tags": [
	    ""
	  ],
	  "links": [
	    ""
	  ]
	}

**Comment by benjaminrosenbaum** [comment]
How about:
```
{
  "specification": "",
  "status": "",
  "thumbnailUrl": "",
  "people": [
    {
      "name": "",
      "url": "",
      "role": ""
    }
  ],
  "organizations": [
    {
      "name": "",
      "url": "",
      "role": ""
    }
  ],
  "geography": "",
  "type": "",
  "data": [
    {
      "name": "",
      "url": ""
    }
  ],
  "tags": [
    ""
  ],
  "links": [
    ""
  ]
}
```
"People" vs. "organizations" makes it unambiguous where an entity goes (where "team" and "entities" might lead to confusion), while delegating to the "role" field the question of why you're listing the entity. You might for instance list a person who's not strictly speaking on the team -- maybe a liaison or oversight person or individual client -- and that will be unambiguous based on role.

I do wonder if role should be an enum, or at least if there should be a set of standard roles listed somewhere.

**Comment by emanuelfeld** [comment]
e.g. https://github.com/DCgov/poirot/blob/master/civic.json

**Comment by stvnrlly** [comment]
I still think that the project overall should have contact options, but otherwise this might work. And yes, making `role` an enumerated field is probably a good way to go, although it will require a little more thinking.

**Comment by emanuelfeld** [comment]
Could that be addressed by adding back in twitter, email as person attributes? My intention was just to allow multiple people as contacts, not to remove the contact attribute.

**Comment by emanuelfeld** [comment]
Update to address contact concern raised by @stvnrlly https://gist.github.com/emanuelfeld/02b3d2569f67a4b4f4a8

**Pull request merged**
