### PR TITLE
Terrys leadership details and the Pygments fix

### PR DESCRIPTION
**Pull request by trycrmr**

### CODE REVIEW

**Comment by stvnrlly** [comment]
The capitalization thing seems a little weird, but it looks like we should be using `rouge` instead of `pygments` anyway: https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change.

**Comment by stvnrlly** [comment]
I'd make the changes directly here, but don't want to do a PR to this PR. If you can change the following two lines in `_config.yml`, I think we're good:

```
markdown: kramdown
highlighter: rouge
```

If you run into issues building based on `example-post.html` or `example-post.md`, just add a blank line to the top of the file.

**Comment by trycrmr** [comment]
Done. Also found and fixed the problem of my work github notifications burying non-work github notifications :-)

**Comment by trycrmr** [comment]
Also adds a link to the subdomain request form @mkalish put together on the Resources page.

**Comment by trycrmr** [comment]
:-)

**Pull request merged**
